import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/app/**/*.{ts,tsx}",
  ],
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        chart: {
          "1": "hsl(var(--chart-1))", "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))", "4": "hsl(var(--chart-4))", "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar))",
          foreground: "hsl(var(--sidebar-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
        },
      },
      borderRadius: {
        lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)",
        "2xl": "1rem", "3xl": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, #6c5ce7 0%, #2dd4bf 100%)",
        "gradient-purple":  "linear-gradient(135deg, #6c5ce7 0%, #a78bfa 100%)",
        "gradient-teal":    "linear-gradient(135deg, #2dd4bf 0%, #0ea5e9 100%)",
        "gradient-warm":    "linear-gradient(135deg, #f59e0b 0%, #f43f5e 100%)",
        "gradient-cool":    "linear-gradient(135deg, #4f46e5 0%, #2dd4bf 100%)",
        "gradient-dark":    "linear-gradient(135deg, #1e1b4b 0%, #0f172a 100%)",
        "gradient-radial":  "radial-gradient(var(--tw-gradient-stops))",
        "grid-pattern":     "linear-gradient(to right, rgba(108,92,231,0.06) 1px, transparent 1px), linear-gradient(to bottom, rgba(108,92,231,0.06) 1px, transparent 1px)",
        "dot-pattern":      "radial-gradient(circle, rgba(108,92,231,0.15) 1px, transparent 1px)",
      },
      backgroundSize: {
        "grid-sm": "24px 24px",
        "grid-md": "40px 40px",
        "grid-lg": "64px 64px",
        "dot-sm":  "16px 16px",
        "dot-md":  "24px 24px",
      },
      boxShadow: {
        "card":    "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        "card-md": "0 4px 16px rgba(0,0,0,0.08), 0 2px 6px rgba(0,0,0,0.04)",
        "card-lg": "0 8px 32px rgba(0,0,0,0.12), 0 4px 12px rgba(0,0,0,0.06)",
        "purple":  "0 8px 32px rgba(108,92,231,0.25), 0 2px 8px rgba(108,92,231,0.1)",
        "teal":    "0 8px 32px rgba(45,212,191,0.25), 0 2px 8px rgba(45,212,191,0.1)",
        "glow-sm": "0 0 16px rgba(108,92,231,0.2)",
        "glow-md": "0 0 32px rgba(108,92,231,0.25), 0 0 64px rgba(108,92,231,0.08)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in":        { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-in-down":   { from: { opacity: "0", transform: "translateY(-12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "scale-in":       { from: { opacity: "0", transform: "scale(0.94)" }, to: { opacity: "1", transform: "scale(1)" } },
        "slide-up":       { from: { opacity: "0", transform: "translateY(20px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-left":     { from: { opacity: "0", transform: "translateX(-20px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        "float":          { "0%,100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-8px)" } },
        "float-slow":     { "0%,100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-14px)" } },
        "shimmer":        { "100%": { transform: "translateX(100%)" } },
        "spin-slow":      { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "pulse-glow":     { "0%,100%": { opacity: "0.6" }, "50%": { opacity: "1" } },
        "bounce-in":      { "0%": { opacity: "0", transform: "scale(0.3)" }, "50%": { opacity: "1", transform: "scale(1.05)" }, "100%": { transform: "scale(1)" } },
        "gradient-shift": { "0%,100%": { backgroundPosition: "0% 50%" }, "50%": { backgroundPosition: "100% 50%" } },
        "count-up":       { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "ping-once":      { "0%": { transform: "scale(1)", opacity: "1" }, "75%,100%": { transform: "scale(2)", opacity: "0" } },
      },
      animation: {
        "accordion-down":  "accordion-down 0.18s ease-out",
        "accordion-up":    "accordion-up 0.18s ease-out",
        "fade-in":         "fade-in 0.3s cubic-bezier(0.16,1,0.3,1) forwards",
        "fade-in-down":    "fade-in-down 0.3s cubic-bezier(0.16,1,0.3,1) forwards",
        "scale-in":        "scale-in 0.25s cubic-bezier(0.16,1,0.3,1) forwards",
        "slide-up":        "slide-up 0.35s cubic-bezier(0.16,1,0.3,1) forwards",
        "slide-left":      "slide-left 0.3s cubic-bezier(0.16,1,0.3,1) forwards",
        "float":           "float 4s ease-in-out infinite",
        "float-slow":      "float-slow 6s ease-in-out infinite",
        "shimmer":         "shimmer 1.6s ease-in-out infinite",
        "spin-slow":       "spin-slow 12s linear infinite",
        "pulse-glow":      "pulse-glow 2s ease-in-out infinite",
        "bounce-in":       "bounce-in 0.5s cubic-bezier(0.16,1,0.3,1) forwards",
        "gradient-shift":  "gradient-shift 4s ease infinite",
        "count-up":        "count-up 0.5s cubic-bezier(0.16,1,0.3,1) forwards",
        "ping-once":       "ping-once 0.6s cubic-bezier(0,0,0.2,1) forwards",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.16, 1, 0.3, 1)",
        bounce: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
